### ISSUE TITLE
Remove AuthGuards

### ISSUE THREAD

**Issue by paulhobbel** [ItsDizzy/angular2-auth#12]
The AuthGuards are pretty useless, since you can create these yourself.

**Comment by FriOne** [comment]
They are very convinient since projects have the same logic usually. Maybe you just separate them into a module?

**Comment by paulhobbel** [comment]
@FriOne Removed them for now. I don't think it will be a good idea to make a module for guards since everyone handles their routes and authentication different. I could include examples tho
