### ISSUE TITLE
What is response.token 

### ISSUE THREAD

**Issue by outsideMyBox** [ItsDizzy/angular2-auth#15]
Hi,

In the example there is the line 
`this._tokenService.setToken(response.token);`
but the class 'Response' from angular/http doesn't have any field 'token' and I get an error. 
Have I missed something or is it an error in the documentation?

Thanks for this library!

**Comment by paulhobbel** [comment]
Ok so in this case i converted the response to json first with response.json(), my backend returns the token as the token key as follows:
```json
{
    "token": "thegeneratedjwttokenhere"
}
```

Do you understand now?

**Comment by outsideMyBox** [comment]
I get it. Thanks!

**Comment by paulhobbel** [comment]
Alright good to hear 😀
