### ISSUE TITLE
Property 'token' does not exis t on type 'Response'.

### ISSUE THREAD

**Issue by karuppasamy11** [ItsDizzy/angular2-auth#16]
how can i solve this issue,
the give me the proper example file

**Comment by paulhobbel** [comment]
Duplicate of #15
The way to fix it is by converting the response to json first, with `response = response.json()`

**Comment by karuppasamy11** [comment]
okay thnk u.
The problem was solved.

**Comment by karuppasamy11** [comment]
but i have another one problem
TypeError: this._tokenService.getToken is not a function

**Comment by paulhobbel** [comment]
Have you added this in the constructor of your auth service `private _tokenService: TokenService`

**Comment by karuppasamy11** [comment]
i had add this line but still issue

**Comment by paulhobbel** [comment]
Could you create a github gist with the code, or a pastebin post so I can see what you did?

**Comment by karuppasamy11** [comment]
okay

**Comment by karuppasamy11** [comment]
import { Injectable } from '@angular/core';
import { TokenService } from 'angular2-auth';
import {Http, Response} from '@angular/http';
import {Observable} from 'rxjs/Rx';
import { Router } from '@angular/router';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/toPromise';

@Injectable()
export class AuthserviceService {
test:any;
  constructor(private _http: Http, private _tokenService: TokenService,private router:Router) { }
  login(email: string, password: string) {

    return this._http.get(`http://localhost:8080/check?email=${email}&pass=${password}`)
      .map(res => this.processData(res.json()));

  }
  processData(data:any){


    console.log("data"+data.token);

              if(data.token!=null) {




                   this._tokenService.setToken(data.token);
                }
                  return data;
    }

  logout() {
    this._tokenService.removeToken();
  }
canActivate(){

    let token = this._tokenService.getToken();

    if(token && token.token) {
      console.log(token.isExpired());
      return !token.isExpired();
    }
    console.log(token);
    this.router.navigate(['login']);
    return false;

}


}

**Comment by paulhobbel** [comment]
Ooh i see were it is going wrong
Change your login function to this:
```ts
return this._http.get(`http://localhost:8080/check?email=${email}&pass=${password}`)
    .map(res => this.processData.bind(this, res.json()));
```

**Comment by ItsDizzy** [comment]
Ooh i see were it is going wrong
Change your log8n function to this:
```ts
return this._http.get(`http://localhost:8080/check?email=${email}&pass=${password}`)
    .map(res => this.processData.bind(this, res.json()));
```

**Comment by karuppasamy11** [comment]
thnk u
