### ISSUE TITLE
Uncaught (in promise): TokenError: A JWT Token must have 3 parts!

### ISSUE THREAD

**Issue by karuppasamy11** [ItsDizzy/angular2-auth#18]

**Comment by paulhobbel** [comment]
Make sure your api returns a valid Javascript Json Token

**Comment by karuppasamy11** [comment]
how can i identify it is valid or not..
just tell me

**Comment by paulhobbel** [comment]
Fill the generated token you get from your backend in on [this website](http://jwt.io)
Your token should have two dots in it to split it in three parts

**Comment by karuppasamy11** [comment]
thnk u
